# Generated by Django 4.2.2 on 2024-05-07 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailing', verbose_name='в рассылке'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(choices=[('DY', 'раз в день'), ('WK', 'раз в неделю'), ('MN', 'раз в месяц')], default='MN', max_length=2),
        ),
    ]
