# Generated by Django 4.2.2 on 2024-05-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_client_mailing_mailing_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата первой отправки'),
        ),
    ]
