# Generated by Django 4.2.2 on 2024-05-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mailing',
        ),
        migrations.AddField(
            model_name='client',
            name='mailing',
            field=models.ManyToManyField(to='mailing.mailing', verbose_name='в рассылке'),
        ),
    ]
