# Generated by Django 4.2.2 on 2024-05-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_remove_client_mailing_client_mailing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mailing',
        ),
        migrations.AddField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(to='mailing.client', verbose_name='в рассылке'),
        ),
    ]
