# Generated by Django 4.2.2 on 2024-05-08 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_alter_mailing_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='sent_time',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='время отправки рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания рассылки'),
        ),
    ]
