# Generated by Django 4.2.2 on 2024-05-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0012_client_user_mail_user_mailing_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_edit_status', 'can edit status')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
